version: "2"

networks:
  reverse-proxy:
    external: true

volumes:
  esdata:
    driver: local

services:
    elasticsearch:
        restart: always
        image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
        container_name: activecollab-ellasticsearch
        networks:
            reverse-proxy:
              aliases:
                - collab.elasticsearch
        environment:
            - http.host=0.0.0.0
            - transport.host=0.0.0.0
            - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
        volumes:
            - ./elasticsearch:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
            - 9300:9300
        mem_limit: 3g

    mysql:
        image: mysql
        container_name: activecollab-mysql
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        networks:
            reverse-proxy:
              aliases:
                - collab.db
        environment:
            - MYSQL_ROOT_PASSWORD=youtouchmytralala
        volumes:
          - "./mysql:/var/lib/mysql"

    activecollab:
        build: .
        container_name: activecollab-app
        links:
            - mysql
            - elasticsearch
        restart: always
        networks:
            reverse-proxy:
                aliases:
                  - collab.app
        volumes:
            - "./activecollab:/var/www"
            - "./nginx:/etc/nginx"
        ports:
            - "8082:80"
