version: '3.1'

volumes:
  elastic-data:
    external: true
  mysql-data:
    external: true

services:
    elasticsearch:
        image: elasticsearch:6.5.4
        restart: unless-stopped
        volumes:
          - elastic-data:/usr/share/elasticsearch/data
    mysql:
        image: mysql
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD=youtouchmytralala
        volumes:
          - mysql-data:/var/lib/mysql
    activecollab:
        build: .
        links:
            - elasticsearch
            - mysql
        restart: unless-stopped
        volumes:
            - "./activecollab:/var/www"
        ports:
            - "32922:80"
